// packages/docs/.vitepress/examples/react/basic-map.tsx
import {
  MapBase,
  MapFeatures,
  MapMesh,
} from '@d3-maps/react'
import { use } from 'react'

const mapDataPromise = import('@d3-maps/atlas/world/countries/countries-110m').then((m) => m.default)

export default function BasicExample(): JSX.Element {
  const mapData = use(mapDataPromise)

  return (
    <MapBase>
      <MapFeatures data={mapData} />
      <MapMesh data={mapData} />
    </MapBase>
  )
}

// packages/docs/.vitepress/examples/basic-map.vue
<template>
  <MapBase
    v-if="data"
  >
    <MapFeatures :data="data" />
    <MapMesh :data="data" />
  </MapBase>
</template>

<script setup lang="ts">
import type { MapData } from '@d3-maps/vue'

const { default: data } = await import('@d3-maps/atlas/world/countries/countries-110m') as { default: MapData }
</script>
