// packages/docs/.vitepress/examples/react/bubble.tsx
import type {
  MapData,
  ZoomEvent,
} from '@d3-maps/core'

import {
  getInverseZoomScale,
} from '@d3-maps/core'
import {
  Map,
  MapFeatures,
  MapMarker,
  MapZoom,
} from '@d3-maps/react'
import { extent } from 'd3-array'
import { geoAlbersUsa } from 'd3-geo'
import { scaleLinear } from 'd3-scale'
import {
  useEffect,
  useMemo,
  useState,
} from 'react'
import { withBase } from 'vitepress'

interface City {
  city: string
  latitude: number
  longitude: number
  population: number
}

export default function BubbleExample(): JSX.Element {
  const [mapData, setMapData] = useState<MapData>()
  const [cities, setCities] = useState<City[]>([])
  const [markerScale, setMarkerScale] = useState(1)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(false)

  useEffect(() => {
    let isCancelled = false

    async function fetchMap(): Promise<MapData> {
      const response = await fetch(withBase('/example-data/states-10m.json'))
      return response.json()
    }

    async function fetchData(): Promise<City[]> {
      const response = await fetch(withBase('/example-data/us-cities.json'))
      return response.json()
    }

    Promise.all([fetchMap(), fetchData()])
      .then(([loadedMap, loadedCities]) => {
        if (isCancelled) {
          return
        }

        setMapData(loadedMap)
        setCities(loadedCities)
      })
      .catch(() => {
        if (!isCancelled) {
          setError(true)
        }
      })
      .finally(() => {
        if (!isCancelled) {
          setLoading(false)
        }
      })

    return () => {
      isCancelled = true
    }
  }, [])

  const minAndMaxValues = useMemo(() => {
    return extent(cities, (item) => Number(item.population))
  }, [cities])

  const bubbleScale = useMemo(() => {
    const safeDomain: [number, number] = [
      minAndMaxValues[0] ?? 0,
      minAndMaxValues[1] ?? 1,
    ]

    return scaleLinear()
      .domain(safeDomain)
      .range([3, 35])
  }, [
    minAndMaxValues[0],
    minAndMaxValues[1],
  ])

  function updateMarkerScale(event: ZoomEvent): void {
    setMarkerScale(getInverseZoomScale(event))
  }

  if (loading) {
    return <div>Loading...</div>
  }

  if (error || !mapData) {
    return <div>An error occurred</div>
  }

  return (
    <Map
      data={mapData}
      projection={geoAlbersUsa}
    >
      <MapZoom
        maxZoom={100}
        onZoom={updateMarkerScale}
      >
        <MapFeatures />
        <g>
          {
            cities.map((item) => (
              <MapMarker
                key={item.city}
                coordinates={[item.longitude, item.latitude]}
              >
                <circle
                  fill="#ff6f2695"
                  r={bubbleScale(item.population)}
                  transform={`scale(${markerScale})`}
                />
              </MapMarker>
            ))
          }
        </g>
      </MapZoom>
    </Map>
  )
}

// packages/docs/.vitepress/examples/bubble.vue
<template>
  <div v-if="loading">
    Loading...
  </div>
  <div v-else-if="error">
    An error occurred
  </div>
  <Map
    v-else
    :projection="projection"
    :data="mapData"
  >
    <MapZoom
      :max-zoom="100"
      @zoom="updateMarkerScale"
    >
      <MapFeatures />
      <g>
        <MapMarker
          v-for="(item, index) in cities"
          :key="index"
          :coordinates="[item.longitude, item.latitude]"
        >
          <circle
            fill="#ff6f2695"
            :r="setSize(item)"
            :transform="`scale(${markerScale})`"
          />
        </MapMarker>
      </g>
    </MapZoom>
  </Map>
</template>

<script setup lang="ts">
import type { ZoomEvent } from '@d3-maps/core'
import { getInverseZoomScale } from '@d3-maps/core'
import { withBase } from 'vitepress'

import { extent } from 'd3-array'
import { geoAlbersUsa } from 'd3-geo'
import { scaleLinear } from 'd3-scale'
import { computed, onMounted, ref } from 'vue'

interface City {
  city: string
  latitude: number
  longitude: number
  population: number
}

const mapData = ref<unknown>()
const projection = geoAlbersUsa
const cities = ref<City[]>([])
const markerScale = ref(1)
const loading = ref(true)
const error = ref(false)

const minAndMaxValues = computed(() => extent(cities.value, (item) => Number(item.population)))
const scale = computed(() => {
  const domain = minAndMaxValues.value
  const safeDomain: [number, number] = [
    domain?.[0] ?? 0,
    domain?.[1] ?? 1,
  ]
  return scaleLinear()
    .domain(safeDomain)
    .range([3, 35])
})

onMounted(async () => {
  try {
    await Promise.all([fetchMap(), fetchData()])
  } catch {
    error.value = true
  } finally {
    loading.value = false
  }
})

function updateMarkerScale(e: ZoomEvent) {
  markerScale.value = getInverseZoomScale(e)
}

const setSize = (item: City) => scale.value(item.population)

async function fetchMap() {
  const response = await fetch(withBase('/example-data/states-10m.json'))
  mapData.value = await response.json()
}

async function fetchData() {
  const response = await fetch(withBase('/example-data/us-cities.json'))
  cities.value = await response.json()
}
</script>
