// packages/docs/.vitepress/examples/react/zoom.tsx
import type { MapData, ZoomEvent } from '@d3-maps/react'

import {
  MapBase,
  MapFeatures,
  MapGraticule,
  MapMarker,
  MapMesh,
  MapZoom,
} from '@d3-maps/react'
import { geoNaturalEarth1 } from 'd3-geo'
import {
  useEffect,
  useRef,
  useState,
} from 'react'

interface City {
  city: string
  lon: number
  lat: number
}

const initialCities: City[] = [
  { city: 'Minsk', lon: 27.34, lat: 53.54 },
  { city: 'Dili', lon: 125.36, lat: -8.35 },
  { city: 'Dushanbe', lon: 68.48, lat: 38.35 },
  { city: 'Guatemala City', lon: -90.31, lat: 14.37 },
  { city: 'Njamena', lon: 12.1348, lat: 15.0557 },
  { city: 'Tokyo', lon: 139.45, lat: 35.41 },
  { city: 'Georgetown', lon: -58.1, lat: 6.48 },
]

export default function ZoomExample(): JSX.Element | null {
  const [mapData, setMapData] = useState<MapData>()
  const [markerScale, setMarkerScale] = useState(1)
  const currentZoomRef = useRef(1)

  useEffect(() => {
    let isCancelled = false

    async function loadMap(): Promise<void> {
      const { default: payload } = await import('@d3-maps/atlas/world/countries/countries-110m')

      if (!isCancelled) {
        setMapData(payload)
      }
    }

    loadMap()

    return () => {
      isCancelled = true
    }
  }, [])

  function updateMarkerScale(event: ZoomEvent): void {
    if (currentZoomRef.current === event.transform.k) {
      return
    }

    currentZoomRef.current = event.transform.k
    setMarkerScale(1 / event.transform.k)
  }

  return mapData
    ? (
        <MapBase
          data={mapData}
          projection={geoNaturalEarth1}
        >
          <MapZoom onZoom={updateMarkerScale}>
            <MapGraticule border />
            <MapFeatures />
            <MapMesh />
            {
              initialCities.map((item) => (
                <MapMarker
                  key={item.city}
                  coordinates={[item.lon, item.lat]}
                >
                  <g transform={`scale(${markerScale})`}>
                    <text
                      fontSize="14"
                      y={-8}
                      textAnchor="middle"
                    >
                      {item.city}
                    </text>
                    <circle
                      r={3}
                    />
                  </g>
                </MapMarker>
              ))
            }
          </MapZoom>
        </MapBase>
      )
    : null
}

// packages/docs/.vitepress/examples/zoom.vue
<template>
  <MapBase
    v-if="data"
    :data="data"
    :projection="projection"
  >
    <MapZoom @zoom="updateMarkerScale">
      <MapGraticule border />
      <MapFeatures />
      <MapMesh />
      <MapMarker
        v-for="(item, index) in cities"
        :key="index"
        :coordinates="[item.lon, item.lat]"
      >
        <g :transform="`scale(${markerScale})`">
          <text
            font-size="14"
            y="-8"
            text-anchor="middle"
          >
            {{ item.city }}
          </text>
          <circle
            r="3"
          />
        </g>
      </MapMarker>
    </MapZoom>
  </MapBase>
</template>

<script setup lang="ts">
import type { ZoomEvent } from '@d3-maps/vue'

import { geoNaturalEarth1 } from 'd3-geo'
import { onMounted, ref } from 'vue'

interface City {
  city: string
  lon: number
  lat: number
}

const initialCities: City[] = [
  { city: 'Minsk', lon: 27.34, lat: 53.54 },
  { city: 'Dili', lon: 125.36, lat: -8.35 },
  { city: 'Dushanbe', lon: 68.48, lat: 38.35 },
  { city: 'Guatemala City', lon: -90.31, lat: 14.37 },
  { city: 'Njamena', lon: 12.1348, lat: 15.0557 },
  { city: 'Tokyo', lon: 139.45, lat: 35.41 },
  { city: 'Georgetown', lon: -58.1, lat: 6.48 },
]

const data = ref<unknown>()
const projection = geoNaturalEarth1
const cities = ref<City[]>(initialCities)
const markerScale = ref(1)
const currentZoom = ref(1)

onMounted(async () => {
  const { default: mapData } = await import('@d3-maps/atlas/world/countries')
  data.value = mapData
})

function updateMarkerScale(e: ZoomEvent) {
  if (currentZoom.value === e.transform.k) return

  currentZoom.value = e.transform.k
  markerScale.value = 1 / e.transform.k
}
</script>
