// packages/docs/.vitepress/examples/annotations.vue
<template>
  <MapBase :data="data">
    <MapFeatures />
    <template
      v-for="city in cities"
      :key="city.name"
    >
      <MapAnnotation
        :coordinates="city.coordinates"
        :stroke="city.color"
        :length="35"
        :angle="-165"
        :margin="2"
        :stroke-width="2"
      >
        <text
          y="-5"
          text-anchor="middle"
          font-size="12"
          :fill="city.color"
        >
          {{ city.name }}
        </text>
      </MapAnnotation>
      <MapMarker :coordinates="city.coordinates">
        <circle :fill="city.color" r="3" />
      </MapMarker>
    </template>
  </MapBase>
</template>

<script setup lang="ts">
import type { MapData } from '@d3-maps/vue'

interface City {
  name: string
  coordinates: [number, number]
  color: string
}

const cities: City[] = [
  {
    name: 'Paris',
    coordinates: [2.3522, 48.8566],
    color: '#ff6f26',
  },
  {
    name: 'New York',
    coordinates: [-73.935242, 40.73061],
    color: '#60a5fa',
  },
]

const { default: data } = await import('world-atlas/countries-110m.json') as { default: MapData }
</script>

// packages/docs/.vitepress/examples/react/annotations.tsx
import {
  MapAnnotation,
  MapBase,
  MapFeatures,
  MapMarker,
} from '@d3-maps/react'
import { use } from 'react'

interface City {
  name: string
  coordinates: [number, number]
  color: string
}

const cities: City[] = [
  {
    name: 'Paris',
    coordinates: [2.3522, 48.8566],
    color: '#ff6f26',
  },
  {
    name: 'New York',
    coordinates: [-73.935242, 40.73061],
    color: '#60a5fa',
  },
]

const mapDataPromise = import('world-atlas/countries-110m.json').then((m) => m.default)

export default function AnnotationExample(): JSX.Element {
  const mapData = use(mapDataPromise)

  return (
    <MapBase data={mapData}>
      <MapFeatures />
      {cities.map((city) => (
        <MapAnnotation
          key={city.name}
          coordinates={city.coordinates}
          stroke={city.color}
          length={35}
          angle={-165}
          margin={2}
          midpoint={[0, -50]}
          strokeWidth={2}
        >
          <text
            y={-6}
            textAnchor="middle"
            fontSize={12}
            fill={city.color}
          >
            {city.name}
          </text>
        </MapAnnotation>
      ))}
      {cities.map((city) => (
        <MapMarker
          key={`${city.name}-marker`}
          coordinates={city.coordinates}
        >
          <circle
            fill={city.color}
            r={3}
          />
        </MapMarker>
      ))}
    </MapBase>
  )
}
