// packages/docs/.vitepress/examples/basic.vue
<template>
  <MapBase
    v-if="data"
    :data="data"
  >
    <MapFeatures />
    <MapMesh />
  </MapBase>
</template>

<script setup lang="ts">
import type { MapData } from '@d3-maps/core'

import { withBase } from 'vitepress'
import { onMounted, ref } from 'vue'

const data = ref<MapData>()

onMounted(async () => {
  const response = await fetch(withBase('/example-data/countries-110m.json'))
  data.value = await response.json()
})
</script>

// packages/docs/.vitepress/examples/react/basic.tsx
import type { MapData } from '@d3-maps/core'

import {
  MapBase,
  MapFeatures,
  MapMesh,
} from '@d3-maps/react'
import { useEffect, useState } from 'react'
import { withBase } from 'vitepress'

export default function BasicExample(): JSX.Element | null {
  const [mapData, setMapData] = useState<MapData>()

  useEffect(() => {
    let isCancelled = false

    async function loadMap(): Promise<void> {
      const response = await fetch(withBase('/example-data/countries-110m.json'))
      const payload = await response.json()

      if (!isCancelled) {
        setMapData(payload)
      }
    }

    loadMap()

    return () => {
      isCancelled = true
    }
  }, [])

  return mapData
    ? (
        <MapBase data={mapData}>
          <MapFeatures />
          <MapMesh />
        </MapBase>
      )
    : null
}
