// packages/docs/.vitepress/examples/choropleth-map.vue
<template>
  <MapBase
    v-if="mapData && choroplethData.length"
  >
    <MapFeatures
      v-slot="{ features }"
      :data="mapData"
      :transformer="transformer"
    >
      <template
        v-for="feature in features"
        :key="String(feature.key)"
      >
        <MapObject
          v-if="feature.type === 'Feature'"
          :d="feature.d"
          name="feature"
          :style="{
            fill: getFeatureColor(feature),
            stroke: '#777',
          }"
          :styles="{
            hover: {
              opacity: 0.8,
            },
          }"
        />
      </template>
    </MapFeatures>
  </MapBase>
</template>

<script setup lang="ts">
import type {
  MapData,
  MapFeatureData,
  MapFeatureTransformer,
} from '@d3-maps/vue'

import { extent } from 'd3-array'
import { scaleLinear } from 'd3-scale'
import { withBase } from 'vitepress'
import { computed, onMounted, ref } from 'vue'

interface CountryStat {
  id: string
  value: number
}

const mapData = ref<MapData>()
const loading = ref(true)
const error = ref(false)
const choroplethData = ref<CountryStat[]>([])

const minAndMaxValues = computed(() => extent(choroplethData.value, (item) => item.value))
const colorScale = computed(() => {
  const domain = minAndMaxValues.value
  const safeDomain: [number, number] = [
    domain?.[0] ?? 0,
    domain?.[1] ?? 1,
  ]
  return scaleLinear<string>()
    .domain(safeDomain)
    .range(['#e0460030', '#e04600'])
})

onMounted(async () => {
  try {
    await Promise.all([fetchData(), fetchMap()])
  } catch {
    error.value = true
  } finally {
    loading.value = false
  }
})

async function fetchMap() {
  const { default: data } = await import('@d3-maps/atlas/world/countries')
  mapData.value = data
}

async function fetchData() {
  const response = await fetch(withBase('/example-data/choropleth-data.json'))
  const rawData = (await response.json()) as Array<Record<string, unknown>>
  choroplethData.value = rawData.map((item) => {
    const id = item['country-code']
    if (typeof id !== 'string') {
      return { id: '', value: 0 }
    }
    return {
      ...item,
      id,
      value: Number(id),
    }
  })
}

const transformer: MapFeatureTransformer = (features) => {
  return features.map((feature) => {
    if (feature.type !== 'Feature') return feature

    const country = choroplethData.value.find((item) => item.id === String(feature.id))
    const colorValue = country ? colorScale.value(country.value) : ''

    return { ...feature, color: colorValue }
  })
}

function getFeatureColor(feature: MapFeatureData): string {
  return String((feature as MapFeatureData & { color?: string }).color ?? '')
}
</script>

// packages/docs/.vitepress/examples/react/choropleth-map.tsx
import type {
  MapData,
  MapFeature,
  MapFeatureTransformer,
} from '@d3-maps/react'

import {
  MapBase,
  MapFeatures,
  MapObject,
} from '@d3-maps/react'
import { extent } from 'd3-array'
import { scaleLinear } from 'd3-scale'
import {
  useCallback,
  useEffect,
  useMemo,
  useState,
} from 'react'
import { withBase } from 'vitepress'

interface CountryStat {
  id: string
  value: number
}

type ChoroplethFeature = Extract<MapFeature, { type: 'Feature' }> & { color?: string }

export default function ChoroplethMapExample(): JSX.Element {
  const [mapData, setMapData] = useState<MapData>()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(false)
  const [data, setData] = useState<CountryStat[]>([])

  useEffect(() => {
    let isCancelled = false

    async function fetchMap(): Promise<MapData> {
      const { default: mapData } = await import('@d3-maps/atlas/world/countries')
      return mapData
    }

    async function fetchData(): Promise<CountryStat[]> {
      const response = await fetch(withBase('/example-data/choropleth-data.json'))
      const rawData = await response.json()

      return rawData.map((item: Record<string, unknown>) => {
        const id = item['country-code']
        if (typeof id !== 'string') {
          return { id: '', value: 0 }
        }

        return {
          ...item,
          id,
          value: Number(id),
        }
      })
    }

    Promise.all([fetchMap(), fetchData()])
      .then(([loadedMap, loadedData]) => {
        if (isCancelled) {
          return
        }

        setMapData(loadedMap)
        setData(loadedData)
      })
      .catch(() => {
        if (!isCancelled) {
          setError(true)
        }
      })
      .finally(() => {
        if (!isCancelled) {
          setLoading(false)
        }
      })

    return () => {
      isCancelled = true
    }
  }, [])

  const minAndMaxValues = useMemo(() => {
    return extent(data, (item) => item.value)
  }, [data])

  const colorScale = useMemo(() => {
    const safeDomain: [number, number] = [
      minAndMaxValues[0] ?? 0,
      minAndMaxValues[1] ?? 1,
    ]

    return scaleLinear<string>()
      .domain(safeDomain)
      .range(['#e0460030', '#e04600'])
  }, [
    minAndMaxValues[0],
    minAndMaxValues[1],
  ])

  const transformer = useCallback<MapFeatureTransformer>((features) => {
    return features.map((feature) => {
      if (feature.type !== 'Feature') return feature

      const country = data.find((item) => item.id === String(feature.id))
      const colorValue = country ? colorScale(country.value) : ''

      return { ...feature, color: colorValue }
    })
  }, [
    data,
    colorScale,
  ])

  if (loading) {
    return <div>Loading...</div>
  }

  if (error || !mapData) {
    return <div>An error occurred</div>
  }

  return (
    <MapBase>
      <MapFeatures
        data={mapData}
        transformer={transformer}
      >
        {({ features }) => (
          features
            .filter((feature): feature is ChoroplethFeature => feature.type === 'Feature')
            .map((feature) => (
              <MapObject
                key={String(feature.id)}
                d={feature.d}
                name="feature"
                styles={{
                  default: {
                    fill: String(feature.color),
                    stroke: '#777',
                  },
                  hover: {
                    fill: String(feature.color),
                    stroke: '#777',
                    opacity: 0.8,
                  },
                }}
              />
            ))
        )}
      </MapFeatures>
    </MapBase>
  )
}
