// packages/docs/.vitepress/examples/choropleth.vue
<template>
  <div v-if="loading">
    Loading...
  </div>
  <div v-else-if="error">
    An error occurred
  </div>
  <Map
    v-else
    :data-transformer="dataTransformer"
    :data="mapData"
  >
    <MapFeatures v-slot="{ features }">
      <MapFeature
        v-for="feature in features"
        :key="String(feature.id)"
        :data="feature"
        :styles="{
          default: {
            fill: feature.color,
            stroke: 'darkslategray',
          },
          hover: {
            fill: feature.color,
            stroke: 'darkslategray',
            opacity: 0.8,
          },
        }"
      />
    </MapFeatures>
  </Map>
</template>

<script setup lang="ts">
import { extent } from 'd3-array'
import { scaleLinear } from 'd3-scale'
import { withBase } from 'vitepress'
import { computed, onMounted, ref } from 'vue'

interface CountryStat {
  id: string
  value: number
}

const mapData = ref<unknown>()
const loading = ref(true)
const error = ref(false)
const data = ref<CountryStat[]>([])

const minAndMaxValues = computed(() => extent(data.value, (item) => item.value))
const colorScale = computed(() => {
  const domain = minAndMaxValues.value
  const safeDomain: [number, number] = [
    domain?.[0] ?? 0,
    domain?.[1] ?? 1,
  ]
  return scaleLinear<string>()
    .domain(safeDomain)
    .range(['beige', 'darkorange'])
})

onMounted(async () => {
  try {
    await Promise.all([fetchData(), fetchMap()])
  } catch {
    error.value = true
  } finally {
    loading.value = false
  }
})

async function fetchMap() {
  const response = await fetch(withBase('/example-data/countries-110m.json'))
  mapData.value = await response.json()
}

async function fetchData() {
  const response = await fetch(withBase('/example-data/choropleth-data.json'))
  const rawData = await response.json()
  data.value = rawData.map((item) => {
    const id = item['country-code']
    return {
      ...item,
      id,
      value: Number(id) * Math.random(),
    }
  })
}

function dataTransformer(features: any[]) {
  return features.map((feature) => {
    const country = data.value.find((item) => item.id === feature.id)
    const colorValue = country ? colorScale.value(country.value) : '#eee'

    return { ...feature, color: colorValue }
  })
}
</script>

// packages/docs/.vitepress/examples/react/choropleth.tsx
import type {
  MapData,
  MapFeature,
} from '@d3-maps/core'

import {
  MapFeature as D3MapFeature,
  Map,
  MapFeatures,
} from '@d3-maps/react'
import { extent } from 'd3-array'
import { scaleLinear } from 'd3-scale'
import {
  useCallback,
  useEffect,
  useMemo,
  useState,
} from 'react'
import { withBase } from 'vitepress'

interface CountryStat {
  id: string
  value: number
}

export default function ChoroplethExample(): JSX.Element {
  const [mapData, setMapData] = useState<MapData>()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(false)
  const [data, setData] = useState<CountryStat[]>([])

  useEffect(() => {
    let isCancelled = false

    async function fetchMap(): Promise<MapData> {
      const response = await fetch(withBase('/example-data/countries-110m.json'))
      return response.json()
    }

    async function fetchData(): Promise<CountryStat[]> {
      const response = await fetch(withBase('/example-data/choropleth-data.json'))
      const rawData = await response.json()

      return rawData.map((item: Record<string, string>) => {
        const id = item['country-code']
        return {
          ...item,
          id,
          value: Number(id) * Math.random(),
        }
      })
    }

    Promise.all([fetchMap(), fetchData()])
      .then(([loadedMap, loadedData]) => {
        if (isCancelled) {
          return
        }

        setMapData(loadedMap)
        setData(loadedData)
      })
      .catch(() => {
        if (!isCancelled) {
          setError(true)
        }
      })
      .finally(() => {
        if (!isCancelled) {
          setLoading(false)
        }
      })

    return () => {
      isCancelled = true
    }
  }, [])

  const minAndMaxValues = useMemo(() => {
    return extent(data, (item) => item.value)
  }, [data])

  const colorScale = useMemo(() => {
    const safeDomain: [number, number] = [
      minAndMaxValues[0] ?? 0,
      minAndMaxValues[1] ?? 1,
    ]

    return scaleLinear<string>()
      .domain(safeDomain)
      .range(['beige', 'darkorange'])
  }, [
    minAndMaxValues[0],
    minAndMaxValues[1],
  ])

  const dataTransformer = useCallback((features: MapFeature[]): MapFeature[] => {
    return features.map((feature) => {
      const country = data.find((item) => item.id === String(feature.id))
      const colorValue = country ? colorScale(country.value) : '#eee'

      return { ...feature, color: colorValue }
    })
  }, [
    data,
    colorScale,
  ])

  if (loading) {
    return <div>Loading...</div>
  }

  if (error || !mapData) {
    return <div>An error occurred</div>
  }

  return (
    <Map
      data={mapData}
      dataTransformer={dataTransformer}
    >
      <MapFeatures>
        {({ features }) => (
          <>
            {
              features.map((feature) => (
                <D3MapFeature
                  key={String(feature.id)}
                  data={feature}
                  styles={{
                    default: {
                      fill: String(feature.color),
                      stroke: 'darkslategray',
                    },
                    hover: {
                      fill: String(feature.color),
                      stroke: 'darkslategray',
                      opacity: 0.8,
                    },
                  }}
                />
              ))
            }
          </>
        )}
      </MapFeatures>
    </Map>
  )
}
