// packages/docs/.vitepress/theme/components/examples/markers.vue
<template>
  <Map
    v-if="mapData"
    :data="mapData"
    :projection="projection"
  >
    <MapFeatures />
    <MapMarker
      v-for="(item, index) in cities"
      :key="index"
      :coordinates="[item.lon, item.lat]"
    >
      <text
        font-size="16"
        y="-6"
        text-anchor="middle"
      >{{ item.city }}</text>
      <circle
        fill="#3eaf7c"
        r="3"
      />
    </MapMarker>
  </Map>
</template>

<script setup lang="ts">
import { geoEqualEarth } from 'd3-geo'
import { onMounted, ref } from 'vue'

interface City {
  city: string
  lon: number
  lat: number
}

const cities: City[] = [
  { city: 'Minsk', lon: 27.34, lat: 53.54 },
  { city: 'Dili', lon: 125.36, lat: -8.35 },
  { city: 'Dushanbe', lon: 68.48, lat: 38.35 },
  { city: 'Njamena', lon: 12.1348, lat: 15.0557 },
  { city: 'Malabo', lon: 8.47, lat: 3.45 },
  { city: 'Tokyo', lon: 139.45, lat: 35.41 },
  { city: 'Georgetown', lon: -58.1, lat: 6.48 },
]

const mapData = ref<unknown>()
const projection = geoEqualEarth

onMounted(async () => {
  const response = await fetch('https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json')
  mapData.value = await response.json()
})
</script>

// packages/docs/.vitepress/examples/react/markers.tsx
import type { MapData } from '@d3-maps/react'

import {
  MapBase,
  MapFeatures,
  MapGraticule,
  MapMarker,
  MapMesh,
} from '@d3-maps/react'
import { useEffect, useState } from 'react'

interface City {
  city: string
  lon: number
  lat: number
}

const cities: City[] = [
  { city: 'Minsk', lon: 27.34, lat: 53.54 },
  { city: 'Dili', lon: 125.36, lat: -8.35 },
  { city: 'Dushanbe', lon: 68.48, lat: 38.35 },
  { city: 'Njamena', lon: 12.1348, lat: 15.0557 },
  { city: 'Malabo', lon: 8.47, lat: 3.45 },
  { city: 'Tokyo', lon: 139.45, lat: 35.41 },
  { city: 'Georgetown', lon: -58.1, lat: 6.48 },
]

export default function MarkersExample(): JSX.Element | null {
  const [mapData, setMapData] = useState<MapData>()

  useEffect(() => {
    let isCancelled = false

    async function loadMap(): Promise<void> {
      const { default: payload } = await import('world-atlas/countries-110m.json')

      if (!isCancelled) {
        setMapData(payload)
      }
    }

    loadMap()

    return () => {
      isCancelled = true
    }
  }, [])

  return mapData
    ? (
        <MapBase data={mapData}>
          <MapGraticule border />
          <MapFeatures />
          <MapMesh />
          {
            cities.map((item) => (
              <MapMarker
                key={item.city}
                coordinates={[item.lon, item.lat]}
              >
                <text
                  fontSize="14"
                  y={-6}
                  textAnchor="middle"
                >
                  {item.city}
                </text>
                <circle
                  r={3}
                />
              </MapMarker>
            ))
          }
        </MapBase>
      )
    : null
}
