// packages/vue/src/components/MapElement.vue
<template>
  <component
    :is="tag"
    v-bind="events"
    :style="style"
  >
    <slot />
  </component>
</template>

<script setup lang="ts">
import type { MapElementProps } from '@d3-maps/core'
import type { StyleValue } from 'vue'

import { toRef } from 'vue'

import { useInteraction } from '../hooks/useInteraction'

type MapElementPathProps = MapElementProps<StyleValue> & {
  tag?: 'path'
}

type MapElementGroupProps = MapElementProps<StyleValue> & {
  tag?: 'g'
}

type Props = MapElementPathProps | MapElementGroupProps

const props = withDefaults(defineProps<Props>(), { tag: 'path' })

const { style, ...events } = useInteraction(toRef(props, 'styles'))
</script>

// packages/react/src/components/MapElement.tsx
'use client'

import type { MapElementProps as CoreMapElementProps } from '@d3-maps/core'
import type {
  CSSProperties,
  ReactElement,
  ReactNode,
  SVGProps,
} from 'react'

import { useInteraction } from '../hooks/useInteraction'

type MapElementBaseProps = CoreMapElementProps<CSSProperties>

interface MapElementPathProps
  extends Omit<SVGProps<SVGPathElement>, 'children' | 'd'>,
  MapElementBaseProps {
  tag?: 'path'
  d?: string
}

interface MapElementGroupProps
  extends SVGProps<SVGGElement>,
  MapElementBaseProps {
  tag: 'g'
  children?: ReactNode
}

export type MapElementProps = MapElementPathProps | MapElementGroupProps

export function MapElement(props: MapElementProps): ReactElement {
  const {
    tag = 'path',
    styles,
    style: baseStyle,
    ...elementProps
  } = props
  const { style: interactionStyle, ...events } = useInteraction<Element>({
    styles,
    ...elementProps,
  })
  const style = {
    ...baseStyle,
    ...interactionStyle,
  }

  if (tag === 'g') {
    return (
      <g
        {...elementProps as MapElementGroupProps}
        style={style}
        {...events}
      />
    )
  }

  return (
    <path
      {...elementProps as MapElementPathProps}
      style={style}
      {...events}
    />
  )
}
