// packages/vue/src/components/MapFeature.vue
<template>
  <path
    :d="path"
    :style="style"
    v-bind="events"
    name="feature"
  />
</template>

<script setup lang="ts">
import type { MapFeatureProps } from '@d3-maps/core'
import type { StyleValue } from 'vue'

import {
  computed,
  toRef,
} from 'vue'

import { useMapContext } from '../hooks/useMapContext'
import { useMapObject } from '../hooks/useMapObject'

const props = defineProps<MapFeatureProps<StyleValue>>()

const { style, ...events } = useMapObject(toRef(props, 'styles'))

const context = useMapContext()

const path = computed(() => context.value.path(props.data) ?? undefined)
</script>

// packages/react/src/components/MapFeature.tsx
'use client'

import type { MapFeatureProps as CoreMapFeatureProps } from '@d3-maps/core'
import type {
  CSSProperties,
  ReactElement,
  SVGProps,
} from 'react'

import { useMemo } from 'react'

import { useMapContext } from '../hooks/useMapContext'
import { useMapObject } from '../hooks/useMapObject'

export interface MapFeatureProps
  extends CoreMapFeatureProps<CSSProperties>,
  Omit<SVGProps<SVGPathElement>, 'children' | 'd' | 'style'> {}

export function MapFeature({
  data,
  styles,
  ...props
}: MapFeatureProps): ReactElement | null {
  const context = useMapContext()

  const path = useMemo(() => {
    return context.path(data) ?? undefined
  }, [context, data])

  const { style, ...events } = useMapObject<SVGPathElement>({
    styles,
    ...props,
  })

  return (
    <path
      {...props}
      d={path}
      style={style}
      name="feature"
      {...events}
    />
  )
}
