// packages/vue/src/components/MapMesh.vue
<template>
  <path
    :d="path"
    data-d3m="mesh"
    fill="none"
  />
</template>

<script setup lang="ts">
import type { MapMeshProps } from '@d3-maps/core'

import { renderMesh } from '@d3-maps/core'
import { computed } from 'vue'

import { useMapContext } from '../hooks/useMapContext'

const props = defineProps<MapMeshProps>()
const context = useMapContext()

const path = computed<string | undefined>(
  () => renderMesh(context.value, props.data, props.objectKey, props.filter) ?? undefined,
)
</script>

// packages/react/src/components/MapMesh.tsx
'use client'

import type { MapMeshProps as CoreMapMeshProps } from '@d3-maps/core'
import type {
  ReactElement,
  SVGProps,
} from 'react'

import {
  renderMesh,
} from '@d3-maps/core'
import { useMemo } from 'react'

import { useMapContext } from '../hooks/useMapContext'

export interface MapMeshProps
  extends Omit<SVGProps<SVGPathElement>, 'children' | 'd' | 'filter'>,
  CoreMapMeshProps {}

export function MapMesh({
  data,
  objectKey,
  filter,
  fill = 'none',
  ...props
}: MapMeshProps): ReactElement | null {
  const context = useMapContext()

  const path = useMemo(
    () => renderMesh(context, data, objectKey, filter) ?? undefined,
    [context, data, objectKey, filter],
  )

  return (
    <path
      d={path}
      data-d3m="mesh"
      fill={fill}
      {...props}
    />
  )
}
