// packages/vue/src/components/MapObjects.vue
<template>
  <g name="objects">
    <slot :objects="objects">
      <MapObject
        v-for="{ key, d } in objects"
        :key="key"
        :d="d"
        :styles="styles"
        name="object"
      />
    </slot>
  </g>
</template>

<script setup lang="ts">
import type {
  MapObjectData,
  MapObjectsProps,
} from '@d3-maps/core'
import type { StyleValue } from 'vue'

import {
  makeMapObjects,
  resolveMapData,
  resolveMapDataRef,
} from '@d3-maps/core'
import { computed } from 'vue'

import { useMapContext } from '../hooks/useMapContext'
import MapObject from './MapObject.vue'

const props = defineProps<MapObjectsProps<StyleValue>>()

defineSlots<{
  default?: (props: { objects: MapObjectData[] }) => unknown
}>()

const context = useMapContext()
const objects = computed<MapObjectData[]>(() => {
  if (props.data == null && props.objectKey == null && props.dataTransformer == null && props.getKey == null) {
    return context.value.objects
  }

  const [resolvedData, resolvedObjectKey] = resolveMapDataRef(
    props,
    context.value,
  )
  if (resolvedData == null) return []

  const objectData = resolveMapData(
    resolvedData,
    resolvedObjectKey,
    props.dataTransformer,
  )

  return makeMapObjects(objectData, context.value.path, props.getKey)
})
</script>

// packages/react/src/components/MapObjects.tsx
'use client'

import type {
  MapObjectsProps as CoreMapObjectsProps,
  MapObjectData,
} from '@d3-maps/core'
import type {
  CSSProperties,
  ReactElement,
  ReactNode,
  SVGProps,
} from 'react'

import {
  makeMapObjects,
  resolveMapData,
  resolveMapDataRef,
} from '@d3-maps/core'
import { useMemo } from 'react'

import { useMapContext } from '../hooks/useMapContext'
import { MapObject } from './MapObject'

interface MapObjectsRenderProps {
  objects: MapObjectData[]
}

type MapObjectsChildren = ReactNode | ((props: MapObjectsRenderProps) => ReactNode)
type MapObjectsElementProps = Omit<SVGProps<SVGGElement>, 'children'>

export interface MapObjectsProps
  extends MapObjectsElementProps,
  CoreMapObjectsProps<CSSProperties> {
  children?: MapObjectsChildren
}

function isRenderProp(children: MapObjectsChildren | undefined): children is (props: MapObjectsRenderProps) => ReactNode {
  return typeof children === 'function'
}

export function MapObjects({
  data,
  objectKey,
  dataTransformer,
  getKey,
  styles,
  children,
  ...groupProps
}: MapObjectsProps): ReactElement {
  const context = useMapContext()

  const objects = useMemo(() => {
    if (data == null && objectKey == null && dataTransformer == null && getKey == null) {
      return context.objects
    }

    const [resolvedData, resolvedObjectKey] = resolveMapDataRef(
      { data, objectKey },
      context,
    )
    if (resolvedData == null) return []

    const objectData = resolveMapData(
      resolvedData,
      resolvedObjectKey,
      dataTransformer,
    )

    return makeMapObjects(objectData, context.path, getKey)
  }, [context, data, objectKey, dataTransformer, getKey])

  const resolvedChildren = isRenderProp(children)
    ? children({ objects })
    : children

  return (
    <g
      {...groupProps}
      name="objects"
    >
      {
        resolvedChildren
        ?? objects.map(({ key, d }) => (
          <MapObject
            key={key}
            d={d}
            styles={styles}
            name="object"
          />
        ))
      }
    </g>
  )
}
