// packages/vue/src/components/MapZoom.vue
<template>
  <g
    ref="container"
    name="zoom"
  >
    <slot />
  </g>
</template>

<script setup lang="ts">
import type {
  ZoomEvent,
  ZoomProps,
} from '@d3-maps/core'

import {
  applyZoomGroupTransform,
  applyZoomTransform,
  createZoomBehavior,
  setupZoom,
} from '@d3-maps/core'
import {
  computed,
  onMounted,
  ref,
  watch,
} from 'vue'

import { useMapContext } from '../hooks/useMapContext'

const props = withDefaults(defineProps<ZoomProps>(), {
  center: () => [0, 0] as [number, number],
  zoom: 1,
  minZoom: 1,
  maxZoom: 8,
})

const emit = defineEmits<{
  (event: 'zoomstart', payload: ZoomEvent): void
  (event: 'zoom', payload: ZoomEvent): void
  (event: 'zoomend', payload: ZoomEvent): void
}>()

const container = ref<SVGGElement | null>(null)
const context = useMapContext()

const zoomBehavior = computed(() => {
  return createZoomBehavior(context?.value, {
    minZoom: props.minZoom,
    maxZoom: props.maxZoom,
    config: props.config,
    onZoomStart: (event) => emit('zoomstart', event),
    onZoom: (event) => {
      applyZoomGroupTransform(container.value, event.transform)
      emit('zoom', event)
    },
    onZoomEnd: (event) => emit('zoomend', event),
  })
})

onMounted(() => {
  watch(
    zoomBehavior,
    (behavior) => {
      if (!container.value) return
      setupZoom({
        element: container.value,
        behavior,
        center: props.center,
        zoom: props.zoom,
      })
    },
    {
      immediate: true,
    },
  )
  watch(
    () => [zoomBehavior.value, props.center[0], props.center[1], props.zoom],
    () => {
      if (!container.value) return
      applyZoomTransform({
        element: container.value,
        behavior: zoomBehavior.value,
        center: props.center,
        zoom: props.zoom,
      })
    },
  )
})

defineExpose({
  container,
  zoomBehavior,
})
</script>

// packages/react/src/components/MapZoom.tsx
'use client'

import type {
  ZoomEvent,
  ZoomProps,
} from '@d3-maps/core'
import type {
  ReactElement,
  ReactNode,
  SVGProps,
} from 'react'

import {
  applyZoomGroupTransform,
  applyZoomTransform,
  createZoomBehavior,
  setupZoom,
  ZOOM_DEFAULTS,
} from '@d3-maps/core'
import {
  useEffect,
  useMemo,
  useRef,
} from 'react'

import { InsideZoomContext } from '../hooks/useInsideZoom'
import { useLatest } from '../hooks/useLatest'
import { useMapContext } from '../hooks/useMapContext'

export interface MapZoomProps
  extends ZoomProps,
  Omit<SVGProps<SVGGElement>, 'children' | 'onZoom'> {
  children?: ReactNode
  onZoomStart?: (event: ZoomEvent) => void
  onZoom?: (event: ZoomEvent) => void
  onZoomEnd?: (event: ZoomEvent) => void
}

export function MapZoom({
  center,
  zoom,
  minZoom = ZOOM_DEFAULTS.minZoom,
  maxZoom = ZOOM_DEFAULTS.maxZoom,
  config,
  onZoomStart,
  onZoom,
  onZoomEnd,
  children,
  className,
  ...groupProps
}: MapZoomProps): ReactElement {
  const containerRef = useRef<SVGGElement | null>(null)
  const skipNextTransformSyncRef = useRef(false)
  const context = useMapContext()

  const onZoomStartRef = useLatest(onZoomStart)
  const onZoomRef = useLatest(onZoom)
  const onZoomEndRef = useLatest(onZoomEnd)

  const resolvedCenter = center ?? ZOOM_DEFAULTS.center
  const resolvedZoom = zoom ?? ZOOM_DEFAULTS.zoom
  const centerX = resolvedCenter[0]
  const centerY = resolvedCenter[1]

  const zoomBehavior = useMemo(() => {
    return createZoomBehavior(context, {
      minZoom,
      maxZoom,
      config,
      onZoomStart: (event) => {
        onZoomStartRef.current?.(event)
      },
      onZoom: (event) => {
        applyZoomGroupTransform(containerRef.current, event.transform)
        onZoomRef.current?.(event)
      },
      onZoomEnd: (event) => {
        onZoomEndRef.current?.(event)
      },
    })
  }, [
    context,
    minZoom,
    maxZoom,
    config,
  ])

  useEffect(() => {
    skipNextTransformSyncRef.current = true

    setupZoom({
      element: containerRef.current,
      behavior: zoomBehavior,
      center: resolvedCenter,
      zoom: resolvedZoom,
    })
  }, [zoomBehavior])

  useEffect(() => {
    if (skipNextTransformSyncRef.current) {
      skipNextTransformSyncRef.current = false
      return
    }

    applyZoomTransform({
      element: containerRef.current,
      behavior: zoomBehavior,
      center: [centerX, centerY],
      zoom: resolvedZoom,
    })
  }, [
    zoomBehavior,
    centerX,
    centerY,
    resolvedZoom,
  ])

  const mergedClassName = className
    ? `d3-map-zoom ${className}`
    : 'd3-map-zoom'

  return (
    <InsideZoomContext.Provider value={true}>
      <g
        {...groupProps}
        ref={containerRef}
        className={mergedClassName}
        name="zoom"
      >
        {children}
      </g>
    </InsideZoomContext.Provider>
  )
}
