// packages/react/src/components/Map.tsx
'use client'

import type {
  MapConfig,
  MapContext,
} from '@d3-maps/core'
import type {
  ReactElement,
  ReactNode,
  SVGProps,
} from 'react'

import { makeMapContext } from '@d3-maps/core'
import { useMemo } from 'react'

import { MapProvider } from './MapContext'

type MapRenderProp = (context: MapContext) => ReactNode

export interface MapProps
  extends MapConfig,
  Omit<SVGProps<SVGSVGElement>, keyof MapConfig | 'children'> {
  children?: ReactNode | MapRenderProp
}

function isRenderProp(children: MapProps['children']): children is MapRenderProp {
  return typeof children === 'function'
}

export function Map({
  width,
  height,
  aspectRatio,
  projection,
  projectionConfig,
  data,
  dataTransformer,
  children,
  className,
  ...svgProps
}: MapProps): ReactElement {
  const context = useMemo(() => {
    return makeMapContext({
      width,
      height,
      aspectRatio,
      projection,
      projectionConfig,
      data,
      dataTransformer,
    })
  }, [
    width,
    height,
    aspectRatio,
    projection,
    projectionConfig,
    data,
    dataTransformer,
  ])

  const resolvedChildren = isRenderProp(children)
    ? children(context)
    : children

  return (
    <MapProvider context={context}>
      <svg
        {...svgProps}
        className={`d3-map ${className ?? ''}`}
        viewBox={`0 0 ${context.width} ${context.height}`}
      >
        {resolvedChildren}
      </svg>
    </MapProvider>
  )
}

// packages/vue/src/components/Map.vue
<template>
  <MapProvider :context="context">
    <svg
      :viewBox="`0 0 ${context.width} ${context.height}`"
      v-bind="$attrs"
      class="d3-map"
    >
      <slot v-bind="context" />
    </svg>
  </MapProvider>
</template>

<script setup lang="ts">
import type {
  MapConfig,
  MapContext,
} from '@d3-maps/core'
import { makeMapContext } from '@d3-maps/core'
import { computed } from 'vue'
import { MapProvider } from './MapContext'

const props = defineProps<MapConfig>()

defineSlots<{
  default?: (props: MapContext) => unknown
}>()

const context = computed<MapContext>(() => makeMapContext({
  width: props.width,
  height: props.height,
  aspectRatio: props.aspectRatio,
  projection: props.projection,
  projectionConfig: props.projectionConfig,
  data: props.data,
  dataTransformer: props.dataTransformer,
}))
</script>
