// packages/react/src/components/MapGeometries.tsx
'use client'

import type {
  MapGeometriesProps as CoreMapGeometriesProps,
  RenderedGeometry,
} from '@d3-maps/core'
import type {
  CSSProperties,
  ReactElement,
  ReactNode,
  SVGProps,
} from 'react'

import { useMapContext } from '../hooks/useMapContext'
import { MapObject } from './MapObject'

interface MapGeometriesRenderProps {
  geometries: RenderedGeometry[]
}

type MapGeometriesChildren = ReactNode | ((props: MapGeometriesRenderProps) => ReactNode)
type MapGeometriesElementProps = Omit<SVGProps<SVGGElement>, 'children'>

export interface MapGeometriesProps
  extends MapGeometriesElementProps,
  CoreMapGeometriesProps<CSSProperties> {
  children?: MapGeometriesChildren
}

function isRenderProp(children: MapGeometriesChildren | undefined): children is (props: MapGeometriesRenderProps) => ReactNode {
  return typeof children === 'function'
}

export function MapGeometries({
  styles,
  children,
  ...groupProps
}: MapGeometriesProps): ReactElement {
  const context = useMapContext()
  const geometries = context.geometries

  const resolvedChildren = isRenderProp(children)
    ? children({ geometries })
    : children

  return (
    <g
      {...groupProps}
      name="geometries"
    >
      {
        resolvedChildren
        ?? geometries.map(({ key, d }) => (
          <MapObject
            key={key}
            d={d}
            styles={styles}
            name="geometry"
          />
        ))
      }
    </g>
  )
}

// packages/vue/src/components/MapGeometries.vue
<template>
  <g name="geometries">
    <slot :geometries="geometries">
      <MapObject
        v-for="{ key, d } in geometries"
        :key="key"
        :d="d"
        :styles="styles"
        name="geometry"
      />
    </slot>
  </g>
</template>

<script setup lang="ts">
import type { MapGeometriesProps, RenderedGeometry } from '@d3-maps/core'
import type { StyleValue } from 'vue'

import { computed } from 'vue'

import { useMapContext } from '../hooks/useMapContext'
import MapObject from './MapObject.vue'

defineProps<MapGeometriesProps<StyleValue>>()

const context = useMapContext()
const geometries = computed<RenderedGeometry[]>(() => context.value.geometries)
</script>
