// packages/react/src/components/MapLine.tsx
'use client'

import type { MapLineProps as CoreMapLineProps } from '@d3-maps/core'
import type {
  CSSProperties,
  ReactElement,
  SVGProps,
} from 'react'

import { getLinePath } from '@d3-maps/core'
import { useMemo } from 'react'

import { useMapContext } from '../hooks/useMapContext'
import { MapObject } from './MapObject'

export interface MapLineProps
  extends CoreMapLineProps<CSSProperties>,
  Omit<SVGProps<SVGPathElement>, 'children' | 'd' | 'style'> {}

export function MapLine({
  coordinates,
  cartesian = false,
  custom = false,
  curve,
  midpoint,
  styles,
  name = 'line',
  fill = 'none',
  ...props
}: MapLineProps): ReactElement {
  const context = useMapContext()

  const path = useMemo(() => {
    return getLinePath(context, {
      coordinates,
      custom,
      curve,
      cartesian,
      midpoint,
    })
  }, [
    context,
    coordinates,
    custom,
    curve,
    cartesian,
    midpoint,
  ])

  return (
    <MapObject
      {...props}
      d={path}
      styles={styles}
      fill={fill}
      name={name}
    />
  )
}

// packages/vue/src/components/MapLine.vue
<template>
  <MapObject
    v-bind="pathAttrs"
    :d="path"
    :fill="fill"
    :styles="styles"
  />
</template>

<script setup lang="ts">
import type { MapLineProps } from '@d3-maps/core'
import type { StyleValue } from 'vue'

import { getLinePath } from '@d3-maps/core'
import {
  computed,
  useAttrs,
} from 'vue'

import { useMapContext } from '../hooks/useMapContext'
import MapObject from './MapObject.vue'

defineOptions({
  inheritAttrs: false,
})

const props = withDefaults(defineProps<MapLineProps<StyleValue>>(), {
  cartesian: false,
  custom: false,
})

const attrs = useAttrs()

const context = useMapContext()

const path = computed<string | undefined>(() => {
  return getLinePath(
    context.value,
    {
      coordinates: props.coordinates,
      custom: props.custom,
      curve: props.curve,
      cartesian: props.cartesian,
      midpoint: props.midpoint,
    },
  )
})

const pathName = computed(() => (attrs.name as string | undefined) ?? 'line')
const fill = computed(() => (attrs.fill as string | undefined) ?? 'none')
const pathAttrs = computed(() => ({
  ...attrs,
  name: pathName.value,
}))
</script>
