// packages/react/src/components/MapMarker.tsx
'use client'

import type { MapMarkerProps as CoreMapMarkerProps } from '@d3-maps/core'
import type {
  CSSProperties,
  ReactElement,
  SVGProps,
} from 'react'

import { getMarkerTransform } from '@d3-maps/core'
import { useMemo } from 'react'

import { useMapContext } from '../hooks/useMapContext'
import { useMapObject } from '../hooks/useMapObject'

export interface MapMarkerProps
  extends CoreMapMarkerProps<CSSProperties>,
  Omit<SVGProps<SVGGElement>, 'style'> {
  name?: string
}

export function MapMarker({
  coordinates,
  styles,
  children,
  name = 'marker',
  ...props
}: MapMarkerProps): ReactElement | null {
  const context = useMapContext()

  const transform = useMemo(() => {
    if (!coordinates) return undefined
    return getMarkerTransform(context, coordinates)
  }, [
    context,
    coordinates?.[0],
    coordinates?.[1],
  ])

  const { style, ...events } = useMapObject<SVGGElement>({
    styles,
    ...props,
  })

  if (!transform) return null

  return (
    <g
      {...props}
      transform={transform}
      style={style}
      name={name}
      {...events}
    >
      {children}
    </g>
  )
}

// packages/vue/src/components/MapMarker.vue
<template>
  <g
    :transform="transform"
    :style="style"
    v-bind="events"
    name="marker"
  >
    <slot />
  </g>
</template>

<script setup lang="ts">
import type { MapMarkerProps as CoreMapMarkerProps } from '@d3-maps/core'
import type { StyleValue } from 'vue'

import { getMarkerTransform } from '@d3-maps/core'
import {
  computed,
  toRef,
} from 'vue'

import { useMapContext } from '../hooks/useMapContext'
import { useMapObject } from '../hooks/useMapObject'

type MapMarkerProps = CoreMapMarkerProps<StyleValue>

const props = withDefaults(defineProps<MapMarkerProps>(), {
  coordinates: () => [0, 0],
})

const context = useMapContext()

const transform = computed(() => {
  return getMarkerTransform(context?.value, props.coordinates)
})

const { style, ...events } = useMapObject(toRef(props, 'styles'))
</script>
